const CONFIG = {
    titleWeb: "hello",
    introTitle: 'bạn ',
    introDesc: `bị điên hả`,
    btnIntro: '^^HiHi^^',
    title: 'bạn bị điên đúng khônh',
    desc: 'bạn bị điên phải không?',
    btnYes: 'đúng rồi <33',
    btnNo: 'Không nha:3',
    question: 'Trên thế giới hơn 7 tỉ người mà sao bạn lại điên<3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'mình bị điên <33333333',
    mess: 'Mình biết mà',
    messDesc: 'bạn bị điên thật hả.',
    btnAccept: 'đúng rồi <3',
    
